config/routes.rb
Rails.application.routes.draw do
  resources :customer_types
  resources :reports
  resources :finances do
    collection do
      get :amortization
    end
  end
  resources :customers
  resources :cars do
    member do
      get 'markup'
    end
  end

  resources :quotes do
   member do
      get 'quote'
    end
  end
  resources :salespeople
  resources :sale_managers
  resources :searches

  get 'dashboard/index'

   root 'dashboard#index'

end

app/models/finance.rb
class Finance < ActiveRecord::Base
  belongs_to :quote
  belongs_to :report
  before_save :add_report, :checkDropDown, :payment_plan_finalize

  def checkDropDown
    if self.payment_type == 'Cash'
      self.interest = 'N/A'
      self.period = 'N/A'
      self.finalize_price = self.principal
    end
   end


  def self.calculate_amortization_table(principal = 0,interest = 0,period = 0)
    Rails.logger.debug "Inputs: #{principal} #{interest} #{period}"
    calculation = []
    number_of_month = (period * 12.0)-1.0
    interest_per_period = (interest/100.0)/ 12.0
    # number_per_payment = (principal*interest_per_period)/(1.0-(1.0+interest_per_period)**(-1.0*(period*12.0)))
     number_per_payment = (BigDecimal(principal)*((BigDecimal(interest)/100.0)/ 12.0))/(1.0-(1.0+((BigDecimal(interest)/100.0)/ 12.0))**(-1.0*(BigDecimal(period)*12.0)))
    count = 0
    principal = BigDecimal(principal)
    (0..number_of_month).each do
      calculation << count+= 1
      calculation << '$%.2f' % number_per_payment
      interest_per_month = principal *  interest_per_period
      calculation << '$%.2f' % interest_per_month
      principal_per_month = BigDecimal(number_per_payment) - BigDecimal(interest_per_month)
      calculation << '$%.2f' % principal_per_month
      ending_balance = principal -= principal_per_month
      if ending_balance < 0
        ending_balance = 0
      end
      calculation << '$%.2f' % ending_balance.round(2)
    end
    return calculation
  end

  def calculate_amortization_table
    return self.class.calculate_amortization_table(self.principal,self.interest,self.period)
  end

private
  def add_report
    self.report_id = 1
  end

  def payment_plan_finalize
    if self.payment_type == 'Payment Plan'
      self.finalize_price = ((BigDecimal(self.principal)*((BigDecimal(self.interest)/100.0)/ 12.0))/(1.0-(1.0+((BigDecimal(self.interest)/100.0)/ 12.0))**(-1.0*(BigDecimal(self.period)*12.0))))*(BigDecimal(self.period)*12)
    end
  end
end

app/controllers/finances_controller.rb
class FinancesController < ApplicationController
  before_action :set_finance, only: [:show, :edit, :update, :destroy]

  # GET /finances
  # GET /finances.json
  def index
    @finances = Finance.all
  end

  # GET /finances/1
  # GET /finances/1.json
  def show
    @amortization_array = @finance.calculate_amortization_table
  end

  # GET /finances/new
  def new
    @finance = Finance.new
  end

  # GET /finances/1/edit
  def edit
  end

  # POST /finances
  # POST /finances.json
  def create
    @finance = Finance.new(finance_params)

    respond_to do |format|
      if @finance.save
        format.html { redirect_to @finance, notice: 'Finance was successfully created.' }
        format.json { render :show, status: :created, location: @finance }
      else
        format.html { render :new }
        format.json { render json: @finance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /finances/1
  # PATCH/PUT /finances/1.json
  def update
    respond_to do |format|
      if @finance.update(finance_params)
        format.html { redirect_to @finance, notice: 'Finance was successfully updated.' }
        format.json { render :show, status: :ok, location: @finance }
      else
        format.html { render :edit }
        format.json { render json: @finance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /finances/1
  # DELETE /finances/1.json
  def destroy
    @finance.destroy
    respond_to do |format|
      format.html { redirect_to finances_url, notice: 'Finance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def amortization
    rate = params[:rate]
    time = params[:time]
    principal = params[:principal]
    @amortization_array = Finance.calculate_amortization_table(principal.to_d,rate.to_d, time.to_i)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_finance
      @finance = Finance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def finance_params
      params.require(:finance).permit(:quote_id, :report_id, :payment_type, :interest, :period, :principal, :finalize_price)
    end
end

app/helpers/finances_helper.rb
module FinancesHelper

  def payment_type
    [
        ['Cash'],
        ['Payment Plan']
    ]
  end

  def num_period
    [
        ['3'],
        ['4'],
        ['5']
    ]
  end

  def customer_name(name)
    Quote.find(name).customer.fname
  end

end

app/views/finances/_amortization_table.erb
<table width="30%">
  <th>Month</th>
  <th>Payment</th>
  <th>Interest</th>
  <th>Principal</th>
  <th>Ending Balance</th>
  <% @amortization_array.each_slice(5) do |num|  %>
      <tr>
        <% num.each do |n| %>
            <td> <%= n %></td>
        <% end %>
      </tr>
  <% end %>

</table>


app/views/finances/_form.html.erb
<%= form_for(@finance) do |f| %>
  <% if @finance.errors.any? %>
        <div id="error_explanation" xmlns="http://www.w3.org/1999/html">
      <h2><%= pluralize(@finance.errors.count, "error") %> prohibited this finance from being saved:</h2>

      <ul>
      <% @finance.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :quote %><br>
    <%= f.collection_select :quote_id, Quote.where(:toa => true), :id, :full_quote, { :prompt => '--Select a Quote--' } %>
  </div>
    <div id="quote_list">
      <table>
        <thead>
        <th>Customer Quote</th>
        </thead>
        <tbody>
        <td>Quote Number: <span id="quote"></span></td>
        </tbody>
      </table>
    </div>
  <div class="field">
    <%= f.label :payment_type, 'Payment Type' %><br>
    <%= f.select :payment_type, ['Cash', 'Payment Plan'], { :prompt => '--Select a Payment Type--' }%>
  </div>
    <div class ="field">
      <%= f.label :principal%></br>
      <%= f.text_field :principal %>
    </div>
  <div id="Payment_plan">
    <%= f.label :interest, 'Interest Rate(%) :' %>
    <%= f.text_field :interest rescue 'N/A'%><br>
    <%= f.label :period, 'Yearly :' %>
    <%= f.select :period, options_for_select(num_period),{}, class: 'form-control', include_blank: true%><br>
  </div>
  <div class="actions">
    <br>
    <%= f.submit %>
  </div>
    <hr>
<% end %>

<!-- Table will be inserted here -->
<div id="amortization-table" class="table-format"></div>

app/views/finances/amortization.js.erb
$('#amortization-table').html("<%= j (render 'amortization_table') %>")

app/views/finances/edit.html.erb
<h1>Editing Finance</h1>

<%= render 'form' %>

<%= link_to 'Show', @finance %> |
<%= link_to 'Back', finances_path %>

app/views/finances/index.html.erb
<p id="notice"><%= notice %></p>

<h1> Finances</h1>
<h3><%= link_to 'Add New Finance', new_finance_path %></h3>
<hr>
<table>
  <thead>
    <tr>
      <th>Quote Number</th>
      <th>Customer Name</th>
      <th>Car Model</th>
      <th>Payment type</th>
      <th>Initiate Price</th>
      <th>Finalize Price</th>
      <th>Finalize Data Complete</th>
      <th colspan="2">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @finances.each do |finance| %>
      <tr>
        <td><%= finance.quote_id %></td>
        <td><%= finance.quote.customer.full_Cust_name %></td>
        <td><%= finance.quote.car.full_model %></td>
        <td><%= finance.payment_type %></td>
        <td><%= number_to_currency(finance.principal) %></td>
        <td><%= number_to_currency(finance.finalize_price) %></td>
        <td><%= finance.created_at.to_formatted_s(:long_ordinal) %></td>
        <td><%= link_to 'Show', finance %></td>
        <td><%= link_to 'Edit', edit_finance_path(finance) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/finances/new.html.erb
<h1>New Finance</h1>

<%= render 'form' %>

<%= link_to 'Back', finances_path %>

app/views/finances/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= "#{@finance.quote.customer.full_Cust_name}'s Finalize Price" %></h1>
<p>
  <strong>Date:</strong>
  <%= @finance.created_at.to_formatted_s(:long_ordinal) %><br>
  <strong>Payment type:</strong>
  <%= @finance.payment_type %><br>
  <strong>Principal:</strong>
  <%= number_to_currency(@finance.principal) %><br>
  <% if @finance.payment_type == "Payment Plan" %>
  <strong>Interest:</strong>
  <%= number_to_percentage(@finance.interest, precision: 0) %><br>
  <strong>Years:</strong>
  <%= @finance.period %><br>
<% end  %>
</p>
<hr>
<% if @finance.payment_type == "Payment Plan"  %>
    <%= render 'amortization_table' %>
<%end %>
<br>
<%= link_to 'Edit', edit_finance_path(@finance) %> |
<%= link_to 'Back', finances_path %>