config/routes.rb
Rails.application.routes.draw do
  resources :customer_types
  resources :reports
  resources :finances do
    collection do
      get :amortization
    end
  end
  resources :customers
  resources :cars do
    member do
      get 'markup'
    end
  end

  resources :quotes do
   member do
      get 'quote'
    end
  end
  resources :salespeople
  resources :sale_managers
  resources :searches

  get 'dashboard/index'

   root 'dashboard#index'

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :quotes
  belongs_to :customer_type

  def full_Cust_name
    "#{fname.capitalize} #{lname.capitalize}"
  end

  #Searc
  def self.search(search)
    if search
      where('fname LIKE ? OR lname LIKE ?', "%#{search}%", "%#{search}%")
    else
       self.all
    end
  end


  #validation
  validates :fname, presence: true,
            format: { with: /\A[a-zA-Z]+\z/,
                      message: "only allows letters" }
  validates :lname, presence: true,
            format: { with: /\A[a-zA-Z]+\z/,
                      message: "only allows letters" }
  validates :address,
            presence: true
  validates :phone,
            presence: true,
            length: {minimum: 10, maximum: 11}
  validates :state,
            presence: true
  validates :city,
            presence: true

  end

app/models/customer_type.rb
class CustomerType < ActiveRecord::Base
  has_many :customers
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.search(params[:search])
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:fname, :lname, :phone, :address, :state, :city, :customer_type_id)
    end
end

app/helpers/customers_helper.rb
module CustomersHelper

  def us_states
    [
        ['Alabama', 'AL'],
        ['Alaska', 'AK'],
        ['Arizona', 'AZ'],
        ['Arkansas', 'AR'],
        ['California', 'CA'],
        ['Colorado', 'CO'],
        ['Connecticut', 'CT'],
        ['Delaware', 'DE'],
        ['District of Columbia', 'DC'],
        ['Florida', 'FL'],
        ['Georgia', 'GA'],
        ['Hawaii', 'HI'],
        ['Idaho', 'ID'],
        ['Illinois', 'IL'],
        ['Indiana', 'IN'],
        ['Iowa', 'IA'],
        ['Kansas', 'KS'],
        ['Kentucky', 'KY'],
        ['Louisiana', 'LA'],
        ['Maine', 'ME'],
        ['Maryland', 'MD'],
        ['Massachusetts', 'MA'],
        ['Michigan', 'MI'],
        ['Minnesota', 'MN'],
        ['Mississippi', 'MS'],
        ['Missouri', 'MO'],
        ['Montana', 'MT'],
        ['Nebraska', 'NE'],
        ['Nevada', 'NV'],
        ['New Hampshire', 'NH'],
        ['New Jersey', 'NJ'],
        ['New Mexico', 'NM'],
        ['New York', 'NY'],
        ['North Carolina', 'NC'],
        ['North Dakota', 'ND'],
        ['Ohio', 'OH'],
        ['Oklahoma', 'OK'],
        ['Oregon', 'OR'],
        ['Pennsylvania', 'PA'],
        ['Puerto Rico', 'PR'],
        ['Rhode Island', 'RI'],
        ['South Carolina', 'SC'],
        ['South Dakota', 'SD'],
        ['Tennessee', 'TN'],
        ['Texas', 'TX'],
        ['Utah', 'UT'],
        ['Vermont', 'VT'],
        ['Virginia', 'VA'],
        ['Washington', 'WA'],
        ['West Virginia', 'WV'],
        ['Wisconsin', 'WI'],
        ['Wyoming', 'WY']
    ]
  end
end

app/views/customers/_customer.html.erb
<tr>
          <td><%= customer.fname.capitalize %></td>
          <td><%= customer.lname.capitalize %></td>
          <td><%=  number_to_phone(customer.phone,area_code: true) %></td>
          <td><%= customer.address %></td>
          <td><%= customer.state %></td>
          <td><%= customer.city %></td>
          <td><%= customer.customer_type.name rescue 'n/a' %></td>
          <td><%= link_to 'Show', customer %></td>
          <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
          <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fname, 'First Name' %><br>
    <%= f.text_field :fname, :placeholder => "e.g. Thomas" %>
  </div>
  <div class="field">
    <%= f.label :lname, 'Last Name' %><br>
    <%= f.text_field :lname, :placeholder => "e.g. Bank" %>
  </div>
  <div class="field">
    <%= f.label :phone, 'Phone Number' %><br>
    <%= f.text_field :phone, :placeholder => "e.g. 8323183180" %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address, :placeholder => "e.g. 132 broadway st." %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.select :state, options_for_select(us_states),{}, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
    <div class="field">
      <%= f.label :customer_type %><br>
      <%= f.collection_select :customer_type_id, CustomerType.all, :id, :name %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Customers</h1>
<h3><%= link_to 'Add New Customer', new_customer_path %></h3>
<hr>
<%= form_tag customers_path, :method => 'get' do %>
    <p>
      <%=  "Search by name :" %>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Search", :name => nil %>
    </p>
<% end %>
<p><%= link_to "Advance Search", new_search_path%></p>
<hr>
<table>
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Phone</th>
      <th>Address</th>
      <th>State</th>
      <th>City</th>
      <th>Customer Type</th>
      <th colspan="3">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.fname.capitalize %></td>
        <td><%= customer.lname.capitalize %></td>
        <td><%=  number_to_phone(customer.phone,area_code: true) %></td>
        <td><%= customer.address %></td>
        <td><%= customer.state %></td>
        <td><%= customer.city %></td>
        <td><%= customer.customer_type.name rescue 'n/a' %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

  <h1><%= @customer.full_Cust_name %></h1>
<hr>
<p>
  <strong>Phone:</strong>
  <%= number_to_phone(@customer.phone,area_code: true) %>
</p>

<p>
  <strong>Address:</strong>
  <%= @customer.address %>
</p>

<p>
  <strong>State:</strong>
  <%= @customer.state.upcase %>
</p>
<p>
  <strong>City:</strong>
  <%= @customer.city %>
</p>

<p>
  <strong>Customer Status:</strong>
  <%= @customer.customer_type.name %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>