config/routes.rb
Rails.application.routes.draw do
  resources :customer_types
  resources :reports
  resources :finances do
    collection do
      get :amortization
    end
  end
  resources :customers
  resources :cars do
    member do
      get 'markup'
    end
  end

  resources :quotes do
   member do
      get 'quote'
    end
  end
  resources :salespeople
  resources :sale_managers
  resources :searches

  get 'dashboard/index'

   root 'dashboard#index'

end

app/controllers/customer_types_controller.rb
class CustomerTypesController < ApplicationController
  before_action :set_customer_type, only: [:show, :edit, :update, :destroy]

  # GET /customer_types
  # GET /customer_types.json
  def index
    @customer_types = CustomerType.all
  end

  # GET /customer_types/1
  # GET /customer_types/1.json
  def show
  end

  # GET /customer_types/new
  def new
    @customer_type = CustomerType.new
  end

  # GET /customer_types/1/edit
  def edit
  end

  # POST /customer_types
  # POST /customer_types.json
  def create
    @customer_type = CustomerType.new(customer_type_params)

    respond_to do |format|
      if @customer_type.save
        format.html { redirect_to @customer_type, notice: 'Customer type was successfully created.' }
        format.json { render :show, status: :created, location: @customer_type }
      else
        format.html { render :new }
        format.json { render json: @customer_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customer_types/1
  # PATCH/PUT /customer_types/1.json
  def update
    respond_to do |format|
      if @customer_type.update(customer_type_params)
        format.html { redirect_to @customer_type, notice: 'Customer type was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer_type }
      else
        format.html { render :edit }
        format.json { render json: @customer_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customer_types/1
  # DELETE /customer_types/1.json
  def destroy
    @customer_type.destroy
    respond_to do |format|
      format.html { redirect_to customer_types_url, notice: 'Customer type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer_type
      @customer_type = CustomerType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_type_params
      params.require(:customer_type).permit(:name)
    end
end

app/helpers/customer_types_helper.rb
module CustomerTypesHelper
end

app/views/customer_types/_form.html.erb
<%= form_for(@customer_type) do |f| %>
  <% if @customer_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer_type.errors.count, "error") %> prohibited this customer_type from being saved:</h2>

      <ul>
      <% @customer_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, :placeholder => "e.g Happy"%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customer_types/edit.html.erb
<h1>Editing Customer Type</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer_type %> |
<%= link_to 'Back', customer_types_path %>

app/views/customer_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Customer Types</h1>
<h3><%= link_to 'Add New Customer Type', new_customer_type_path %></h3>
<hr>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @customer_types.each do |customer_type| %>
      <tr>
        <td><%= customer_type.name %></td>
        <td><%= link_to 'Show', customer_type %></td>
        <td><%= link_to 'Edit', edit_customer_type_path(customer_type) %></td>
        <td><%= link_to 'Destroy', customer_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/customer_types/new.html.erb
<h1>New Customer Type</h1>

<%= render 'form' %>

<%= link_to 'Back', customer_types_path %>

app/views/customer_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @customer_type.name %>
</p>

<%= link_to 'Edit', edit_customer_type_path(@customer_type) %> |
<%= link_to 'Back', customer_types_path %>