config/routes.rb
Rails.application.routes.draw do
  resources :customer_types
  resources :reports
  resources :finances do
    collection do
      get :amortization
    end
  end
  resources :customers
  resources :cars do
    member do
      get 'markup'
    end
  end

  resources :quotes do
   member do
      get 'quote'
    end
  end
  resources :salespeople
  resources :sale_managers
  resources :searches

  get 'dashboard/index'

   root 'dashboard#index'

end

app/models/report.rb
class Report < ActiveRecord::Base
  has_many :finances


  def calculation_total_gross_revenue
    total_gross_revenue = Finance.sum("finalize_price") - Car.where(:sold => false).sum("msrp")
  end
  def calculation_net_profit
    net_profit = self.calculation_total_gross_revenue - self.calculation_total_sale_tax
  end
  def calculation_total_sale_tax
    sale_tax = Quote.where(:toa => true).sum("sale_tax")
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
    @calculation_total_gross_revenue = @report.calculation_total_gross_revenue
    @calculation_net_profit = @report.calculation_net_profit
    @calculation_sale_tax = @report.calculation_total_sale_tax
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:name)
    end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.erb
<%= form_for(@report) do |f| %>
  <% if @report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% @report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reports/edit.html.erb
<h1>Editing Report</h1>

<%= render 'form' %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reports</h1>

<table>
  <thead>
    <tr>
      <th>Owner Name</th>
      <th colspan="3">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td><%= report.name %></td>
        <td><%= link_to 'Log In', report, data: { confirm: 'Are you Johnny Dinh?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/reports/new.html.erb
<h1>New Report</h1>

<%= render 'form' %>

<%= link_to 'Back', reports_path %>

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>
<h1><%= "#{@report.name}'s Report" %></h1>
<hr>
<p>
  Total Gross Revenue: <%= number_to_currency(@calculation_total_gross_revenue) %> <br>
  Sale Tax: <%= number_to_currency(@calculation_sale_tax) %> <br>
  Net Profit: <%= number_to_currency(@calculation_net_profit) %>
</p>
<%= link_to 'Edit', edit_report_path(@report) %> |
<%= link_to 'Back', reports_path %>